### ISSUE TITLE
no output on opi_dmx4x

### ISSUE THREAD

**Issue by raystream** [vanvught/h3dmx512-zip#1]
hi 

i have made an sd card with the latest files and connected the opi one to the opi-dmx4x board.
But i get no output out off the dmx outs.

the first line of the oled is: Eth Art-Net 3 RDM_SPI

i have written output=dmx in the artnet.txt but that didnt help.

which jumpers do i have to set on the opi-dmx4x board?
there a 3 for each dmx out which have to been set?

regards, Bjoern Bloehdorn

**Comment by vanvught** [comment]
Hi Bjoern,

The output= parameter in artnet.txt is not used in the dmx_multi version.
The OLED should show -> Active Ports: 4

Please make sure you are using the uImage from -> 
https://github.com/vanvught/h3dmx512-zip/blob/master/opi_emac_artnet_dmx_multi.zip

The first line should show DMX or RDM only.

Please also check with you lighting software/console if the node is discovered. 

![img_2437](https://user-images.githubusercontent.com/4319913/53728523-3ef64980-3e73-11e9-962e-00e04d988206.jpeg)

**Comment by rewolff** [comment]
The jumpers are for the bus-termination. For a first test with a short cable "no jumpers" is just fine.

**Comment by raystream** [comment]
hi

i have flashed the sd card with the actual image and then copied the right files on the sd and renamed them, like described in the manual.
DMXWorkshop discoverd the node.  

the oled show Active Ports: 4 but still RDM_SPI in the first row.

i have a simple LED DMX Tester on the output but no led lights up like there is no signal on the xlr connectors.

**Comment by raystream** [comment]
do i have to set all 3 jumper for each output to enable bus-termination?

**Comment by vanvught** [comment]
> but still RDM_SPI in the first row.

That is pretty odd. The source code https://github.com/vanvught/rpidmx512/blob/master/opi_emac_artnet_dmx_multi/firmware/main.cpp#L181 prints "RDM" or "DMX" only.

Please also make sure that DMX Workshop is showing the "TRANSMIT" status.

![knipsel](https://user-images.githubusercontent.com/4319913/53730604-b084c680-3e78-11e9-9b8e-0897f7315427.PNG)

**Comment by raystream** [comment]
i get this node list:

![image](https://user-images.githubusercontent.com/6542516/53730870-62bc8e00-3e79-11e9-8f19-0fbdbc1bc46b.png)

**Comment by raystream** [comment]
when i disable RDM then the first row of the OLED end with DMX_SPI.

**Comment by vanvught** [comment]
There is "No net data", hence it is not transmitting DMX. Please make sure that the status is "TRANSMIT" for the port under test.

**Comment by rewolff** [comment]
For bus termination, add the middle jumper. The other two might help (but probably don't) if you're using RDM. I need to find time to test it myself or someone needs to tell me what works best.... 
Reports welcome: Things to try with RDM: add the 1-2 and 5-6 jumpers, no jumpers and third case: jumper 1-5 and 2-6 with a small patch-cable. Each of these with yes-or-no termination. Interesting to know if each of these three work for RDM and RDM discovery. Extra things to try: with or without termination for each option.

**Comment by raystream** [comment]
just deleted the spiflash.txt file from the sd card and now the OLEDs first line ends with RDM.
but still no output.
dmxworkshop sends data but the LED Tester on the DMX Output is still dark.
node list still is no net data

**Comment by raystream** [comment]
ok deleting the artnet.txt helped.

**Comment by vanvught** [comment]
When DMX Workshop is showing "No net data" then the Art-Net node is not receiving a DMX universe for the defined ports. 

Please make sure that DMX Workshop is showing the status 'TRANSMIT'

The spiflash.txt configuration file is used for copying the firmware into the SPI flash.

**Comment by vanvught** [comment]
> ok deleting the artnet.txt helped.

Then the Art-Node will use the defaults -> http://www.orangepi-dmx.org/raspberry-pi-art-net-dmx-out/configuration

=> Universe 0

Note that DMX Workshop defaults to Universe 1

**Comment by raystream** [comment]
now my artnet.txt look like:

`net=0
subnet=0
universe=0
enable_rdm=1

short_name=RSM ArtNet Node
long_name=RayStream media ArtNet Node`

and now all is working.

thank you all for your great help
