### ISSUE TITLE
Consistent playback speeds ?

### ISSUE THREAD

**Issue by magdesign** [vanvught/h3dmx512-zip#10]
Hi
I am wondering when you playback a recorded DMX/ArtNet show, is your playback speed consistent or does it vary as well?

Since I saw on [this website](http://www.raspberrypi-dmx.org/showfile-player) that you are also using OLA for your dmx, I am wondering if you can help us to solve this issue on OLA: https://github.com/OpenLightingProject/ola/issues/1677

**Comment by vanvught** [comment]
Hi,

> I am wondering when you playback a recorded DMX/ArtNet show, is your playback speed consistent or does it vary as well?

For sure the playback speed is consistent; the time given in the showfile is the exact wait time between outputs.

> I am wondering if you can help us to solve this issue on OLA: OpenLightingProject/ola#1677

I cannot assist here. I am not working with Linux. I use the OLA showfile format as an example for the plug 'n play feature I have implemented for supporting all kinds of showfile formats.

The issue looks typically the nature of Linux with the kernel interrupts. 

-- Arjan

**Comment by magdesign** [comment]
ok. Thanks!
