### ISSUE TITLE
Multi port pixel prototype boards docs/resources

### ISSUE THREAD

**Issue by cerian** [vanvught/h3dmx512-zip#11]
Hello Arjan,

First off I'd like to thank you for this massive amount of work you have put into this project. It truly is spectacular!
After stumbling upon the project I immediately went and bought a OPi Zero (intended to be used as a pixel controller) and started looking into your custom prototyping boards. 

These are the first custom boards I will order ever (hope to one day have the time to actually learn creating custom PCBs). I stumbled upon the page on how to order from JLCPCB and the guide seems to be working great for the 1x4 Universes board.

However, for both the 4x4 and the 8x4 boards BOM / CPL files are missing from webpage and repository. I tried to install EAGLE and generate the files myself through JLCPCB's EAGLE helpers however the files generated seem to contain no parts (and it seems I have added the missing libraries needed for the parts).

Hope you can help me on my way to getting the boards ordered.

Best regards,
Søren Pedersen

**Comment by vanvught** [comment]
Hi Søren,

As the 4x 4U board is DIL only, there is no BOM and no CPL file on GitHub. 
There is a BOM here -> [http://www.orangepi-dmx.org/orange-pi-dmx512-rdm/ws28xx-configuration/prototype-boards/multi/4-output/bom](http://www.orangepi-dmx.org/orange-pi-dmx512-rdm/ws28xx-configuration/prototype-boards/multi/4-output/bom)

For the 8x 4U there are all the files available for an order at PCBWay with their assembly services -> https://github.com/vanvught/h3dmx512-zip/tree/master/eagle/Orange-Pi-Zero/Pixel8x/P4
I have used PCBWay as JLCPCB does not have all the SMD components in stock.

Hope this helps. 

Greetings, Arjan

**Comment by cerian** [comment]
Hello again Arjan,

Thank you for the quick response! I see. 
So for the 8x4 I wouldn't even need a CPL file for the order at PCBWay but just the mountsmd.zip file. Learning every day.

Cheers!

Best regards,
Søren Pedersen
