### ISSUE TITLE
Unable to open /opi_emac_ltc_smpte.zip

### ISSUE THREAD

**Issue by lmcncola** [vanvught/h3dmx512-zip#12]
Unable to properly unzip /opi_emac_ltc_smpte.zip on Mac OS Big Sur 11.1

'Unable to expand "orangepi_zero.uimage.gz". It is in an unsupported format.'

**Comment by vanvught** [comment]
> 'Unable to expand "orangepi_zero.uimage.gz". It is in an unsupported format.'

There is no need to expand "orangepi_zero.uimage.gz"

**Comment by lmcncola** [comment]
Thank you,  it is understood that the .gz does not get expanded.  That is the message from the OS.   However, the original zip does not expand to a folder with the uImage and .gz file.  Please try it.  On MacOS and Windows, that downloaded file does not produce a folder with 2 files when unzipped like every other package on the list. 

Thank you,

Mike C

**Comment by vanvught** [comment]
Hi Mike,

The zip file does unzip fine on MacOS. There is just one file in it: `orangepi_zero.uImage.gz`

**Comment by vanvught** [comment]
```
arjanvanvught@MacBook-Air h3dmx512-zip-master % unzip opi_emac_ltc_smpte.zip
Archive:  opi_emac_ltc_smpte.zip
  inflating: orangepi_zero.uImage.gz  
arjanvanvught@MacBook-Air h3dmx512-zip-master % 
```

**Comment by lmcncola** [comment]
Thanks Arjan,

It does work.  My confusion was that it didn’t behave like the other modules I was trying and produced the error message when using finder to expand. 

 I am new to pi and your system. You have built a great piece of kit here.  I just need to learn how to use it.

I do have more questions as I dig into this.  I’d like to solve this on my own, but I’m not a developer and will have some questions as I continue to work thru this.

I hope you can put up with me if I ask some dumb questions.  Is there a better way to contact or is this an OK channel to use? 



Thanks,


Mike C
