### ISSUE TITLE
Remote Configuration Tool

### ISSUE THREAD

**Issue by dmpw-jan** [vanvught/h3dmx512-zip#13]
Was working with the ltc firmware on an orangepi-zero and i encountered some strange network behaviour.

Booting from SD Card is no problem. I can see the pi in my network and the Remote Configuration Tool finds the device. But to change something i need to remove the sdcard, since it always loads the sdcard configuration.

But when i remove the sdcard and reboot the device i can no longer find the device in the network. Both with fixed ip and dhcp enabled i get the same problem. It seems like i have to completely flash the sdcard to regain network control which only lasts until first reboot.

PS: i really appreciate your project. It's awesome even if i only use ltc to build custom ltc displays.

**Comment by vanvught** [comment]
> . But to change something i need to remove the sdcard, since it always loads the sdcard configuration.

http://www.orangepi-dmx.org/orange-pi-dmx512-rdm/remote-configuration/spi-flash-boot-process

and

http://www.orangepi-dmx.org/orange-pi-dmx512-rdm/remote-configuration/example-java-ui

_When using this sample Java application, the .txt files on the SDCard takes precedence so any changes you make with the UI will get overwritten by the .txt files on the SDCard if it exists. You only need the SDCard for the initial setup._

**Comment by vanvught** [comment]
>  It seems like i have to completely flash the sdcard to regain network control which only lasts until first reboot.

Please will you check if your Orange Pi Zero has the SPI flash chip on the bottom side?

**Comment by dmpw-jan** [comment]
It has the SPI flash chip on the bottom side. 
But i think i found the trigger. i have  two devices in use currently. Both are flashed with the same sdcard and use the same settings. But when i change the source on one device from systemtime to ltc input AND enable the ntp server it no longer communicates via ethernet.
