### ISSUE TITLE
Drop frames with LTC in

### ISSUE THREAD

**Issue by joakyhsf69** [vanvught/h3dmx512-zip#14]
Hello, I really like the project but I have some problems. When I use the LTC input, randomly, once or twice every 5min, the time code changes to wrong values, that makes the equipment that I have connected to execute wrong cues. How can I make the LTC entry more stable? When I use the internal generator I don't have those frame drops. Thanks

**Comment by vanvught** [comment]
What is the input circuit you are using? When the LTC input is wrongly decoded, then the signal strength might be too low. Thanks, Arjan

cc: @hippyau  @rbarreiros @wyged

**Comment by joakyhsf69** [comment]
I have used the shield that appears on the project website.  If I connect directly the unbalanced signal it doesn't even work for me.  I used a neutrik nte-1 transformer to unbalance the signal

Enviado desde mi iPhone

El 2 jul 2021, a las 8:57, Arjan ***@***.***> escribió:

﻿

What is the input circuit you are using? When the LTC input is wrongly decoded, then the signal strength might be too low. Thanks, Arjan

cc: @hippyau<https://github.com/hippyau> @rbarreiros<https://github.com/rbarreiros> @wyged<https://github.com/wyged>

**Comment by vanvught** [comment]
Basically we can just use one signal of a balanced-output. No need to transform balanced to un-balanced. Anyway the LTC firmware should work fine; I will create a setup in the weekend and see if I can replicate the issue seen. Thanks, Arjan

cc: @hippyau @rbarreiros @wyged

**Comment by joakyhsf69** [comment]
yes, but when I use only one signal, without using an input transformer, the signal is too low and does not work well, from a normal computer output with the volume at 100%

Enviado desde mi iPhone

El 2 jul 2021, a las 11:56, Arjan ***@***.***> escribió:

﻿

Basically we can just use one signal of a balanced-output. No need to transform balanced to un-balanced. Anyway the LTC firmware should work fine; I will create a setup in the weekend and see if I can replicate the issue seen. Thanks, Arjan

cc: @hippyau<https://github.com/hippyau> @rbarreiros<https://github.com/rbarreiros> @wyged<https://github.com/wyged>

**Comment by vanvught** [comment]
Please give this build a test and let me know the outcome. Thanks, Arjan

[orangepi_zero.uImage.gz](https://github.com/vanvught/h3dmx512-zip/files/6756647/orangepi_zero.uImage.gz)

cc: @hippyau @rbarreiros @wyged

**Comment by vanvught** [comment]
Please `all` give this build a good test and let me know the outcome. Many thanks in advance, Arjan
[orangepi_zero.uImage.gz](https://github.com/vanvught/h3dmx512-zip/files/6756985/orangepi_zero.uImage.gz)
cc: @hippyau @rbarreiros @wyged

**Comment by hippyau** [comment]
Hi Arjan,

 I just finished building my the P2 LTC board, tested this latest firmware above,  seems to work perfectly with LTC generator I have,  will do some more testing but looks good to me.   Note i've only tested LTC IN -> ArtTimeCode + MIDI   

![image](https://user-images.githubusercontent.com/36442309/124346100-459e5280-dc20-11eb-8880-887da901aba2.png)

**Comment by joakyhsf69** [comment]
Hello, sorry for the delay in answering. I have tried version 3.1 and it seems much more stable, I don't know where the bug would be, but it seems to be fixed. However, I will continue testing, thank you

**Comment by vanvught** [comment]
@joakyhsf69 

>  sorry for the delay in answering. 

No worries. I'm just glad to hear that V3.1 is working for you. 

>  I don't know where the bug 

It was a classic timer overflow when calculating delta times. 

> However, I will continue testing, thank you

Please use latest I have published here on this GitHub. I will close this issue. Please do open a new issue for V3.1 when needed. Thanks for using my firmware.

Greets, Arjan

cc: @hippyau @rbarreiros @wyged
