### ISSUE TITLE
Conversion from MTC to LTC is not smooth

### ISSUE THREAD

**Issue by joakyhsf69** [vanvught/h3dmx512-zip#15]
Hello again, I have another problem. I am trying to sync video with Resolume Arena through LTC. When I use the internal generator, the video playback is smooth, but when I convert from MTC to LTC the video skips frames and the playback is not smooth. I have tried with MIDI input and with RTPMIDI input, the result is the same. What could be the problem? Thanks

**Comment by vanvught** [comment]
Hi, please will you attach a network trace or RTP-MIDI trace where we can see that all timecode is correctly sent? Thanks, Arjan

cc: @hippyau @rbarreiros @wyged

**Comment by joakyhsf69** [comment]
I'm not sure I know how I can do that. But I tried to send the timecode with two different applications, Reaper and MTC Sender

**Comment by vanvught** [comment]
> I'm not sure I know how I can do that. But I tried to send the timecode with two different applications, Reaper and MTC Sender

 @hippyau Hi Hip, are you able to assist here? I am eager to get this solved.

**Comment by vanvught** [comment]
@joakyhsf69 Do you perhaps have an UART-USB adapter? Then I can give you a debug firmware and the output can be copied here.

**Comment by joakyhsf69** [comment]
I have a usb-ttl, is it the same?

**Comment by vanvught** [comment]
> I have a usb-ttl, is it the same?

Yes, as long as it can work with 3V3 then it is OK.

Just gathering information; Are you sending MIDI CLOCK(BPM) packets as well?

**Comment by joakyhsf69** [comment]
[cid:BEEF0D05-4F19-475C-A2D9-FB85BACA169D-L0-001]

Enviado desde mi iPhone

El 14 jul 2021, a las 20:09, Arjan ***@***.***> escribió:

﻿

I have a usb-ttl, is it the same?

Yes, as long as it can work with 3V3 then it is OK.

Just gathering information; Are you sending MIDI CLOCK(BPM) packets as well?

**Comment by joakyhsf69** [comment]
![IMG_2919](https://user-images.githubusercontent.com/65468792/125673104-a8b40a90-3ae2-4c6b-9c80-9d80ee24706c.jpg)
Is this.
No, I am only sending Timecode, not BPM

**Comment by vanvught** [comment]
> Is this.

Looks good. Just connect the GND's and the TX from OPi to RXD

I will try to reproduce what you are seeing. Most likely I have the time in this weekend.

![OPiZ_uart](https://user-images.githubusercontent.com/4319913/125673374-cc7ad684-fafa-4b00-b4f1-aeef31f8fde2.png)

cc: @hippyau @rbarreiros @wyged

**Comment by joakyhsf69** [comment]
Ok, I'll try tomorrow. What I have done is a slow motion video of the Arena's SMPTE counter, when I send from the generator I see all the frames, but when I convert from midi, it goes two by two

**Comment by hippyau** [comment]
Sorry Arjan,  my MIDI input does not seem to work,  I built the LTC board and MIDI board, but I was not so successful with ordering the correct parts.  The LTC is fine, and I can send MIDI but the MIDI input is not working, so I can't test MIDI to LTC without working out the problem first.

**Comment by hippyau** [comment]
I have found something, but is not directly related to OP issue.  Using my oPi Big Clock as an ArtNet source at 25FPS, and my recently built LTC output oPi board, every now and then, it appears not sequential frames are being sent.  It only happens occasionally, not very often... I had to sit waiting on the record button to capture this.   [vimeo video](https://vimeo.com/575823192/bd4fa17f7f)


This might be an ArtNet TC thing, because it's UDP and not a very good standard.   I could not seem to get rtp-midi to work between two oPi.  

My ADx Systems LTC analyzer is an old but very expensive and reliable bit of broadcast kit.  Still, a couple of no-sequential frames should be 'jammed out' and not very representative of the original issue, just thought worth sharing....

Are you doing literal MIDI directly into to LTC frames, or are you internally generating LTC and chasing the MTC sync?  You could possibly 'jam' a few frames, and see if the MTC catches up.

**Comment by vanvught** [comment]
My believing; there is a challenge with all external updates for LTC output. The LTC output is DMA interrupt based with FIFO data pipeline. Hence there is a robust generation of the LTC signal. @hippyau Maybe you can verify this with using the option LTC Generator (internal source) and your ADx Systems LTC analyzer.

When there is an external event received and the DMA is not yet completed then; 1. that latest event is discarded 2. And the LTC output is duplicated. When a new event arrives in time, then we have skipped 2 frames. 

I will provide a debug firmware where a 'F' is outputted to the debug UART in case we receive an external event and the DMA is not yet finished. The 'F' should appear when a. @joakyhsf69 observes that  a video frame is missing b. @hippyau when ADx Systems LTC analyzer is telling about no-sequential frames.

I've an idea how to solve this. But first some information from the debug firmware. 

cc: @rbarreiros @wyged

**Comment by hippyau** [comment]
Hey Arjan, 

 Good thinking,  I have been playing with internal the last hour, and (if analyser is to be believed), there is some weirdness going on,  but it's unpredictable.  I can eventually correct it by manipulating settings or rebooting.  It possibly be to do with changing the rate and using "Set Rate".  One "gotcha" is my analyser only likes 25FPS, so....

Reproducible:
Reboot with ltc.txt: fps=30
`Set Rate` 25 in UI and hit `Start`
Many "NON-SEQ" frames on the analyser. 

Reboot with ltc.txt: fps=25
hit `Start`
Works perfectly :)

Without rebooting I can randomly, with messing with the UI, eventually get it going without "NON-SEQ"

@joakyhsf69  what rate were using and did you change rates at all?

Cheers,

**Comment by vanvught** [comment]
Thank Hip!

I believe we are getting close to a solution. That FPS change using the remote config interface gives yet another good information. I am trying to get some additional information with network captures and some Linux command line tricks...

**Comment by vanvught** [comment]
[orangepi_zero.uImage.gz](https://github.com/vanvught/h3dmx512-zip/files/6831696/orangepi_zero.uImage.gz)

This `DEBUG` firmware outputs a `'F'` when the DMA is still busy when there is new event received.

It looks like the Art-Net Timecode 30FPS to LTC output is pretty robust. But not perfect; so work to do ;-)

**Comment by joakyhsf69** [comment]
Hello again. I have tried both 25 and 30 fps. In both cases it does the same to me. What works well for me is ARTNET to LTC, just like the internal generator

**Comment by vanvught** [comment]
@joakyhsf69 @hippyau Please find attached the firmware with new designed LTC output. Please do give it a good test and let me know the results. Many thanks!

[orangepi_zero.uImage.gz](https://github.com/vanvught/h3dmx512-zip/files/6832942/orangepi_zero.uImage.gz)

cc:  @rbarreiros @wyged

**Comment by joakyhsf69** [comment]
Sorry, but with this new firmware, the MTC -> LTC conversion doesn't work for me at all. It does not seem to be valid LTC. The ARTNET -> LTC and INTERNAL -> LTC conversion does seem to work fine

**Comment by vanvught** [comment]
@joakyhsf69 Thanks for the feedback.

I am a little but puzzled here.

>  It does not seem to be valid LTC.

There is a same output process for all sources; So I do not understand, yet, why there should be invalid LTC here.


> MTC -> LTC conversion doesn't work for me at all. 
> ARTNET -> LTC and INTERNAL -> LTC conversion does seem to work fine

Both Rtp-MIDI MTC and Art-Net are just network external events. It should not make any differences.

cc: @hippyau @rbarreiros @wyged

**Comment by hippyau** [comment]
Must be the MIDI source or circuitry?

**Comment by vanvught** [comment]
Successfully tested on MacOS:

- ShowKontrol -> TCNet -> OPi -> LTC Out
- ShowKontrol -> Art-Net -> OPi -> LTC Out
- ShowKontrol -> RTP-MIDI [MTC] -> OPi -> LTC Out

[ShowKontrol](https://www.tc-supply.com/showkontrol-live)

cc: @hippyau @rbarreiros @wyged

Next: Building a Windows (7) test/debug environment

**Comment by hippyau** [comment]
I have not been able to test:

 MIDI-Cable -> OPi -> LTC Out

**Comment by joakyhsf69** [comment]
I don't know, but if you tell me how, I'll send you empirical data on the outflow and what happens to me.

**Comment by vanvught** [comment]
@joakyhsf69 I am able to replicate the issue on Windows 7. 

Where MacOS is sending all QF's messages in a single RTP-MIDI packet, from Windows we get just a single QF message per RTP-MIDI packet. And Wireshark does not like the RTP-MIDI packets from Windows, it says; "malformed". However, the QF messages is recognizable. 

I hope to append updated firmware later this evening. 

cc: @hippyau @rbarreiros @wyged

**Comment by vanvught** [comment]
Hi @joakyhsf69  , please will you give the attached firmware a try for `source=rtp-midi` ? Many thanks in advance.

cc: @hippyau @rbarreiros @wyged

[orangepi_zero.uImage.gz](https://github.com/vanvught/h3dmx512-zip/files/6843126/orangepi_zero.uImage.gz)

**Comment by joakyhsf69** [comment]
Yes! RTPMIDI -> LTC conversion now works and runs smoothly. But the MIDI -> LTC conversion still doesn't work. Almost solved

**Comment by vanvught** [comment]
Hi @joakyhsf69 , thanks for the quick feedback. Much appreciated. 

I will work on the DIN-MIDI -> LTC as soon as possible. With the knowledge of the RTP-MIDI implementation , it would take not much effort.

Greets, Arjan

cc: @hippyau @rbarreiros @wyged

**Comment by vanvught** [comment]
Hi @joakyhsf69 , I am working on the DIN-MIDI implementation. Although DIN-MIDI is from the 80’s, you would expect that all platforms would have a same implementation. However MacOS is different from Windows. It’s a lot of debugging work. 

cc: @hippyau @rbarreiros @wyged

**Comment by hippyau** [comment]
Hey Arjan,  but MIDI is MIDI right? A 31250 baud UART.   Quarter frames are quarter frames, full frames (sysex) frames etc are well defined format.  

What is it they are doing differently?   

I get RTP-Midi can support journaling and no-journal and different packets, but that isn't an issue on the 5-pin socket.

**Comment by vanvught** [comment]
Hi Hip,

On the MacOS I see all QF’s in a single stream with the FPS rate. As MacOS is de facto standard for musicians and some professional entertainment software, I am not sure what is happening here. For converting to LTC it is much easier than the MIDI standard where we need 2 frames (8 QF’s) for a full update (which I am seeing on Windows).

At least I need to write code that would support it all.  It’s somehow funny still learning from MIDI ;-) 

![218498749_139725071540047_3027840342945563765_n](https://user-images.githubusercontent.com/4319913/126761046-9cd4653d-b637-4fd7-8429-7dc6c0b3ebd1.png)

**Comment by hippyau** [comment]
what is generating that?    

Yes what you are calling the windows approach is the correct approach and how most hardware devices from the 80's would generate it :)  I have written a MTC generator used by some in professional circles, that conforms to the standard and has never had any problems with it's output, and tested with some good analyzer tools... 

It looks like this implementation is smashing them out in bursts.   I've seen that before (my first generator :) ),  a common strategy is to sync MIDI-IN to an internal free running clock to generate LTC.  Starting with the fisrt message, the sysex full frame, then locking your internal clock to the MTC values regularly (at least once per second i'd suggest).  Some devices don't send the Full Frame (naughty) but then yes you need two frames to make a timecode.


If your incoming TC has some issues, this provides a smoothing option by 'jamming' along outputting LTC for a second, covering this incoming timing issues.

**Comment by vanvught** [comment]
Hi @joakyhsf69 , please will you give the attached firmware a try for `source=midi` ? Many thanks in advance.

cc: @hippyau @rbarreiros @wyged

[orangepi_zero.uImage.gz](https://github.com/vanvught/h3dmx512-zip/files/6870657/orangepi_zero.uImage.gz)

**Comment by joakyhsf69** [comment]
Yes, both the rtpmidi and the din already work fine. Congratulations, and thank you

**Comment by vanvught** [comment]
Thank you Joaquin!
