### ISSUE TITLE
Orange Pi Zero does not boot.

### ISSUE THREAD

**Issue by mattg66** [vanvught/h3dmx512-zip#16]
On the latest release, none of my OPI Zeros will boot on the 1x4 pixel controller firmware. I have tried reflashing to no avail. The ethernet port flashes 3 times and then the red LED blinks every second and the green LED remains illuminated.

Let me know if you require any more information

**Comment by vanvught** [comment]
Hi Matt,

Which protocol ? sACN E1.31 or Art-Net 4?

Thanks, Arjan
