### ISSUE TITLE
No 16x2 I2C LCD display with v3.4 and 3.5

### ISSUE THREAD

**Issue by joakyhsf69** [vanvught/h3dmx512-zip#17]
Hello, with versions 3.4 and 3.5 nothing can be seen on my 16x2 I2C LCD display. With version 3.3 it looks fine. I don't know what would have changed. The rest seems to work but nothing is seen on the display

**Comment by vanvught** [comment]
Which firmware ?

**Comment by joakyhsf69** [comment]
opi_emac_ltc_smpte.zip
 V3.4 and V3.5 dispaly no works
opi_emac_ltc_smpte.zip V3.2 and V3.3 display works

**Comment by vanvught** [comment]
Added: https://github.com/vanvught/rpidmx512/issues/237

**Comment by vanvught** [comment]
I have tried to replicate the issue reported. However, it is working fine for me with both V3.4 and V3.5.

Note: an I2C level shifter should be used.

![IMG_4748](https://user-images.githubusercontent.com/4319913/162738939-9e280fc8-9b7d-48e5-9931-6e11161a464b.jpeg)

**Comment by joakyhsf69** [comment]
what could be my problem?  with v3.3 it works fine for me, but with 3.4 nothing is seen

Enviado desde mi iPhone

El 11 abr 2022, a las 14:39, Arjan ***@***.***> escribió:

﻿

I have tried to replicate the issue reported. However, it is working fine for me with both V3.4 and V3.5.

Note: an I2C level shifter should be used.

[IMG_4748]<https://user-images.githubusercontent.com/4319913/162738939-9e280fc8-9b7d-48e5-9931-6e11161a464b.jpeg>

**Comment by vanvught** [comment]
The LCD code is not changed with v3.4 and 3.5.

![Schermafbeelding 2022-04-18 om 21 49 29](https://user-images.githubusercontent.com/4319913/163867758-315abcf5-0fff-4e0e-b010-35c977a53ce7.png)

@joakyhsf69

**Comment by joakyhsf69** [comment]
https://user-images.githubusercontent.com/65468792/163878782-b27e78d0-941e-4dae-b8c8-a7ad727a5995.mov

**Comment by vanvught** [comment]
@joakyhsf69 Thanks for the video. I am investigating for how to resolve the issue. 
Do you mind changing the I2C address of your display ? 

For example, closing A0, then using I2C address 0x26.

Thanks, Arjan

![image](https://user-images.githubusercontent.com/4319913/163960339-74c9e474-066e-479b-8a8e-412daae8cacc.png)


![image](https://user-images.githubusercontent.com/4319913/163960148-3c2c7905-20dc-47ba-a3a9-0fad0731ed75.png)

**Comment by joakyhsf69** [comment]
I don't care, tell me which direction should I try

**Comment by vanvught** [comment]
> I don't care, tell me which direction should I try

Ok. Give me a day or two. I am working on it.

**Comment by vanvught** [comment]
@joakyhsf69 Herewith the updated firmware. It is working for 16x2 with I2C address 0x26 -> A0 closed.
[orangepi_zero.img.gz](https://github.com/vanvught/h3dmx512-zip/files/8516197/orangepi_zero.img.gz)

**Comment by joakyhsf69** [comment]
I can't update from the "remoteconfigui.jar". It says TFTP Failed.

**Comment by vanvught** [comment]
> I can't update from the "remoteconfigui.jar". It says TFTP Failed.

Please see the new attachment -> https://github.com/vanvught/h3dmx512-zip/issues/17#issuecomment-1103087378

**Comment by joakyhsf69** [comment]
Yes!! Now it seems that it works. Thank you
