### ISSUE TITLE
No 16x2 I2C LCD display well with v3.4 and 3.5 again

### ISSUE THREAD

**Issue by joakyhsf69** [vanvught/h3dmx512-zip#18]
Hello, I am sorry to reopen this issue, but the Display still does not work well for me. Indeed, by adjusting the display trimmer it is visible again, but the startup messages (Network, Rebooting) and the source selection do not appear, only the clock, so now I cannot select the source from the display with the buttons

**Comment by vanvught** [comment]
https://github.com/vanvught/h3dmx512-zip/issues/17
