### ISSUE TITLE
some questions, device.txt

### ISSUE THREAD

**Issue by himijendrix24** [vanvught/h3dmx512-zip#2]
At first, thanks for all the effort that went into this project. 
By now it is quiet impressive and led animations (ws2811, orange pi zero) are flicker-free and without noticeable latency. 

It took some time to get it running, so I wrote down my install procedure at the end.
But there are still some questions left.

1) the device.txt is not visible in the Remote Configuration Manager. In the past it was, I think. Is this a bug?

2) sometimes I had to remove the ethernet cable during boot. Otherwise it wouldn't continue. After plugging it again, it would work fine.

3) led_count=xxx in devices.txt behaves strange. When choosing 680 LEDs, DMX-Workshop tells me that the orange pi has 4 universe as outputs. 
When choosing 681 or more (682 should be the maximum, right ? 512*4/3=682,6...) It shows me only the first universe and tells me that universe 1-3 are "not implemented".
How should this number be used?
Does it affect the frame rate?
What is the actual frame rate when selecting 2 universes?

Thanks & Greetings

################
install procedure
################

1) flash uboot-orangpi_zero.zip to an sd card
2) copy the orangepi_zero.uImage from opi_emac_artnet_dmx.zip as uImage
3) I changed the network.txt to
```
#network.txt
use_dhcp=0
ip_address=192.168.0.70
net_mask=255.255.255.0
default_gateway=192.168.0.1
```
4) added a device.txt
```
led_type=WS2811
led_count=680
```
5) changed artnet.txt
```
#artnet.txt
net=0
subnet=0
universe=0
output=spi
enable_rdm=1
```
6) now insert the sd card and power on
7) after a while unplug, remove the sd card and power on with the ethernet cable attached ---> now the orange pi boots from spi and is found as an artnet node, also with the configuration manager
8) With rdm enabled I can configure it with dmx workshop

**Comment by vanvught** [comment]
> At first, thanks for all the effort that went into this project.

Thanks!

> By now it is quiet impressive and led animations (ws2811, orange pi zero) are flicker-free and without noticeable latency.

The WS28xx timing generated is perfect, hence there should/could be no flickering. The only latency is within the network. The node is optimized in not spending time in non-functional code. 

> 1.    the device.txt is not visible in the Remote Configuration Manager. In the past it was, I think. Is this a bug?

I cannot replicate this issue. Please make sure you have the latest .jar from GitHub.
Also when output= is not set, then it is defaulted to DMX(/RDM) and the _params.txt_ is shown in the UI.
Please also note that the Java UI is just a sample of how the remote management framework can work.

The _devices.txt_ can be retrieved as following:
` echo '?get#devices.txt' | nc -u -p 10501 -w 1 192.168.0.70 10501`
http://www.orangepi-dmx.org/orange-pi-dmx512-rdm/remote-configuration

> 2.   sometimes I had to remove the ethernet cable during boot. Otherwise it wouldn't continue. After plugging it again, it would work fine.

I have never seen this behavior in my environment.  Nor it is reported before. The Ethernet cable should be connected at boot time as there is EMAC negotiation at startup. 

> 3.    led_count=xxx in devices.txt behaves strange. When choosing 680 LEDs, DMX-Workshop tells me that the orange pi has 4 universe as outputs.
>     When choosing 681 or more (682 should be the maximum, right ? 512*4/3=682,6...) It shows me only the first universe and tells me that universe 1-3 are "not implemented".
>     How should this number be used?
>     Does it affect the frame rate?
>     What is the actual frame rate when selecting 2 universes?

The maximum amount of RGB leds is 680 --> 512 / 3 = 170 --> 170 * 4 = 680

When a led_count of 0 or > 680 is provided, then it is defaulted to 170 -> https://github.com/vanvught/rpidmx512/blob/master/lib-ws28xxdmx/src/ws28xxdmxparams.cpp#L130

The maximum updates per second can be found here -> http://www.orangepi-dmx.org/orange-pi-dmx512-rdm/ws28xx-configuration/technical-details
The maximum updates per second is limited to what is possible by the WS28xx chips.

> 7. after a while unplug, remove the sd card and power on with the ethernet cable attached ---> now the orange pi boots from spi and is found as an artnet node, also with the configuration manager

The remote configuration framework works also when booting from SDCard. However, any time when booting from SDCard and there are are .txt files on the SDCard, the SPI flash is re-configured -> http://www.orangepi-dmx.org/orange-pi-dmx512-rdm/remote-configuration/spi-flash-boot-process

> 8. With rdm enabled I can configure it with dmx workshop

The enable_rdm parameter is only applicable when output is DMX/RDM. Otherwise this parameter is not used. DMX Workshop will always find the node when  it is up-and-running.

**Comment by vanvught** [comment]
Hi @himijendrix24 , please may I have an update for this issue? Please will you also check the latest firmware and .jar file? Thanks, Arjan

**Comment by himijendrix24** [comment]
Thanks for you answers Arjan.
Until now there are no further questions, everything I needed worked well. 
You can close the issue. 

I just ordered your raspberry dmx shield to test it as an alternative for the "EUROLITE Art-Net-DMX Node 1" with which I had very bad experiences. If there are any more questions I will ask them here.

**Comment by DCled** [comment]
Hello Arjan van Vught. 
First i want to Thank you for your great work!!
A spent a lot of time on my led project and it got finaly a live.
We make (together with frends) several strips of one meter, with mounth with a WS2811 led stip of 60 led each meter. Every strip has his one connector for power supply. The data signal that is connected tot the SPI pin i going all over the whole strip. (a total of 8 stips together in serial connection)

I use a Orange Pi Zero with your software 

> Art-Net 4 Node : DMX Out / RDM Controller / Pixel Controller
> Pixel controller WS28xx/SK6812/APA102/UCSx903 [Orange Pi Zero]
> 1x 4 Universes {zip}

and finaly it works for now. also with the help en comments of " himijendrix24 " 

The point that i can't fix is that you have to add in the software the total of pixels. (8 x 60 = 480 pixels) but it is not posible te give the maximum of pixels per universe...

I want to drive this led strips with the Jinx or Resolume software, but a softpatch is not zo easy or impossible.

We mounth 2 strips that make a total of 120 pixel. 3 stips make 180 and that are 10 pixels to much for each universe... 

Hopefully you will help me... mayby is there a possibility to give a data word in the divice.txt or artnet.txt??? that is written down on de SD card.

waiting for your respons. Greats DC

**Comment by vanvught** [comment]
> The point that i can't fix is that you have to add in the software the total of pixels. (8 x 60 = 480 pixels) but it is not posible te give the maximum of pixels per universe...

The above does not show how pixel software does work. It is common to work with the first universe, and then assign the pixels continuously. With proper pixel software there is an option skipping DMX slot 511/512. For example see MadMapper:

![Schermafbeelding 2020-02-07 om 09 35 16](https://user-images.githubusercontent.com/4319913/74013852-a96e0e80-498d-11ea-9a8c-c1fa3ca58fdc.png)


> I want to drive this led strips with the Jinx or Resolume software, but a softpatch is not zo easy or impossible.

I have worked with Jinx! in the past and it has a good patch editor where you can assign the pixels similar as can be done in MadMapper. I do not know Resolume, but I have users reporting that Resolume is working fine -> [http://www.orangepi-dmx.org/raspberry-pi-art-net-dmx-out/successfully-tested](http://www.orangepi-dmx.org/raspberry-pi-art-net-dmx-out/successfully-tested). However, I've learned that Resolume is not the best choice for pixel mapping.

> mayby is there a possibility to give a data word in the divice.txt or artnet.txt??? that is written down on de SD card.

I am not sure that the question is. I have documented the devices.txt here -> [http://www.orangepi-dmx.org/orange-pi-dmx512-rdm/ws28xx-configuration](http://www.orangepi-dmx.org/orange-pi-dmx512-rdm/ws28xx-configuration). And the artnet.txt is described here -> [http://www.orangepi-dmx.org/raspberry-pi-art-net-dmx-out/configuration](http://www.orangepi-dmx.org/raspberry-pi-art-net-dmx-out/configuration)

Please note that the SDCard is just needed for installing the firmware on the Orange Pi Zero. Afterwards the remote configuration framework should be used -> [http://www.orangepi-dmx.org/orange-pi-dmx512-rdm/remote-configuration](http://www.orangepi-dmx.org/orange-pi-dmx512-rdm/remote-configuration). With the example UI -> [http://www.orangepi-dmx.org/orange-pi-dmx512-rdm/remote-configuration/example-java-ui](http://www.orangepi-dmx.org/orange-pi-dmx512-rdm/remote-configuration/example-java-ui)

-- Arjan

**Comment by DCled** [comment]
It is a couple of weeks ago.

Thank you for your quick ansure. Finaly the led strip / led project works with Jinx. It take some time to get a good patch, but finaly it works.

Also Madmapper works correctly, your comments help me a lot. Finaly we chose for Jinx.. to run the led strips.

Thank you verry much for your time and software.

Greats, DC.

**Comment by vanvught** [comment]
> Also Madmapper works correctly, your comments help me a lot. Finaly we chose for Jinx.. 

MadMapper has a better sACN / Art-Net implementation as it uses the synchronization process.
