### ISSUE TITLE
LTC first digit blinks

### ISSUE THREAD

**Issue by Chek1905** [vanvught/h3dmx512-zip#20]
Hello. Thanks for the development.
I am using Orange Zero H3 and LES KU-82LTC scoreboard, and I have a problem with displaying the first digit. The first digit blinks (changes its value).
The scoreboard is working properly. I checked using the generated LTC file (https://elteesee.pehrhovey.net).
What could be the problem?
I attach 3 videos and 1 sound LTC from Orange.

[Out from Orange.zip](https://github.com/vanvught/h3dmx512-zip/files/10483215/Out.from.Orange.zip)

**Comment by vanvught** [comment]
The LES KU-82LTC  is not known to me. It is a not supported display -> [https://www.orangepi-dmx.org/9-ltc-smpte-timecode-reader-converter-generator](https://www.orangepi-dmx.org/9-ltc-smpte-timecode-reader-converter-generator)

Do you have a datasheet for the LES KU-82LTC scoreboard?

**Comment by Chek1905** [comment]
https://s-pro.tv/upload/iblock/ku82ltc_m.pdf
Translate:
The KU-82LTC timecode display panel is designed to display the current time in the clockification systems and the timecode in the assembly complexes.
The panel receives an LTC timecode signal with a nominal speed or a speed from 0.5 to 2x of the nominal. The LTC signal input is transformer, galvanically isolated, with a sensitivity from 0.3 to 10 V of full swing.
The high input resistance allows cascading panels by parallel connection. Due to the properties of the LTC signal itself, the signal transmission is insensitive to its polarity, and a wide tolerance for the permissible amplitude of the signals allows you to receive both symmetrical and asymmetric signals.
Technical specifications.
Interface type SMPTE/AES LTC
Connector type RJ-11
Input signal span 0.3-10 V
Power supply of the display panel 9-12V 1 A

**Comment by vanvught** [comment]
Ah..it is a timecode display itself. However, for showing timecode, it is missing 2 digits. 
When there are blinking digits, then most likely the input signal is too low. The output signal from the OPi Zeros is not that strong, it would be best to add an opamp.

**Comment by Chek1905** [comment]
Thanks. I will try.
One more question.
What is the frequency of synchronization with the NTP server?

**Comment by vanvught** [comment]
> What is the frequency of synchronization with the NTP server?

[https://github.com/vanvught/rpidmx512/blob/master/lib-network/src/apps/ntpclient.cpp#L44](https://github.com/vanvught/rpidmx512/blob/master/lib-network/src/apps/ntpclient.cpp#L44)
