### ISSUE TITLE
Raspberry pi 4?

### ISSUE THREAD

**Issue by Cinaeth** [vanvught/h3dmx512-zip#21]
Just wondering if i can use my raspberry pi 4 8 gb ram for the smpte generation? If theres add ons needed? I'm looking to sync a zoom h4n and bmp6k camera

**Comment by vanvught** [comment]
There is no support for the Raspberry Pi boards any more -> https://github.com/vanvught/rpidmx512-zip/issues/6#issuecomment-640098142

LTC SMPTE will also become available for the GD32F -> https://www.gd32-dmx.org
