### ISSUE TITLE
Orange Pi Zero boot problem

### ISSUE THREAD

**Issue by elbarto111111111** [vanvught/h3dmx512-zip#26]
Hi, 
I try to run the LTC SMPTE Timecode on a OPi Zero 3 1GB. I flahsed the uboot-orangpi_zero.img and copied orangepi_zero.uImage.gz from the opi_emac_ltc_smpte.zip renamed to uImage. When I put it into the OPi only the green led on the network adapter starts flashing. But thats it. I cant see anything in the Remote Configuration Manager or ping the OPi. When I start the OPi without the SD it says: `[/int]: Failed to mount /dev/mtdblock4!`
What am I doing wrong?

**Comment by vanvught** [comment]
Hi,

The OPi Zero 3 1GB is not supported.  The supported board is the Orange Pi Zero LTS.

Thanks, Arjan
