### ISSUE TITLE
Various Issues with LTC IN Timecode

### ISSUE THREAD

**Issue by joakyhsf69** [vanvught/h3dmx512-zip#28]
Hello, I haven't used the device for some time, but upon picking it up and updating it to the latest version (4.9), I have encountered several issues that have prevented me from using it.

The main problem is that with LTC IN, the MTC output, both RTP-MIDI and DIN, does not work, and the Artnet output doesn’t work either. I am unsure if anything else has stopped functioning, as I have no way to verify. With the internal generator, both DIN MIDI and Artnet do work, so it doesn’t seem to be a hardware issue.

The case with the RTP output is even stranger, as it doesn’t work with either LTC IN or the internal generator. The MA2, which I am using to receive the TC, shows the numbers but doesn’t turn green, as if the message isn’t arriving correctly. This happens with both LTC IN and the generator.

**Comment by vanvught** [comment]
Moved to https://github.com/vanvught/rpidmx512/issues/294
