### ISSUE TITLE
RemoteConfigUI:  Nothing found

### ISSUE THREAD

**Issue by hippyau** [vanvught/h3dmx512-zip#3]
Hi there, 

I got the UI working with `java -jar RemoteConfigUI.jar` though I don't see my nodes on any network interface, yet I can ping and echo them.  I just get a red Searching message if I refresh or change interface, but can't seem to find anything and presented with two empty boxes where I assume to see stuff.

![image](https://user-images.githubusercontent.com/36442309/61377280-3e23f880-a8e6-11e9-9bac-fea4fb1ed0ae.png)

I can ping them no worries...
```
hip@hip-Alienware-13:~/OrangePi/h3dmx512-zip$ ping 10.0.0.25
PING 10.0.0.25 (10.0.0.25) 56(84) bytes of data.
64 bytes from 10.0.0.25: icmp_seq=1 ttl=64 time=0.336 ms
64 bytes from 10.0.0.25: icmp_seq=2 ttl=64 time=0.237 ms
...

```

Also for example `echo '?list#' | nc -u -p 10501 -w 1 10.0.0.25 10501` returns the correct information or this node `10.0.0.25,sACN E1.31,Pixel,2`.

I have tried refresh, changing interfaces, restarting, changing both PC and nodes IP address ranges and sub-nets to all the usuals, DHCP, sudo, and there are no apparent errors on the console, just the window.   Any ideas?

```
hip@hip-Alienware-13:~/OrangePi/h3dmx512-zip$ java -jar RemoteConfigUI.jar
Linux
wlp1s0
	/fe80:0:0:0:495a:2779:5e6f:62dc%wlp1s0 false false false
	/192.168.1.69 false false false
Local ip: 192.168.1.69
Interface address: 192.168.1.69
No more messages.
No more messages.
No more messages.
wlp1s0
wlp1s0
/fe80:0:0:0:495a:2779:5e6f:62dc%wlp1s0
/192.168.1.69
enp2s0
enp2s0
/fe80:0:0:0:f10f:a22d:2bf7:9a73%enp2s0
/10.0.0.1
/192.168.1.69
lo
isLoopback
Interface address: 10.0.0.1
No more messages.
No more messages.
No more messages.
```

```
hip@hip-Alienware-13:~/OrangePi/h3dmx512-zip$ java --version
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)
```

**Comment by vanvught** [comment]
The Java UI is provided AS-IS (an example -> http://www.orangepi-dmx.org/orange-pi-dmx512-rdm/remote-configuration/example-java-ui). As the command line option is working fine, this issue is considered as an observation. The source code of the sample UI can be found here -> https://github.com/vanvught/rpidmx512/tree/master/RemoteConfigUI/src/org/orangepi/dmx

Please work with Wireshark output and/or add additional logging to the .java code. And add it to the issue.

**Comment by vanvught** [comment]
Working example:

```
@nuc-i5:/development$ java -jar RemoteConfigUI.jar 
Linux
enx002432168476
	/fe80:0:0:0:224:32ff:fe16:8476%enx002432168476 false false false
	/192.168.10.3 false false false
Local ip: 192.168.10.3
Interface address: 192.168.10.3
No more messages.
No more messages.
No more messages.
enx002432168476
enx002432168476
/fe80:0:0:0:224:32ff:fe16:8476%enx002432168476
/192.168.10.3
eno1
eno1
/fe80:0:0:0:f64d:30ff:fe64:d9e5%eno1
/192.168.2.120
lo
isLoopback
Interface address: 192.168.2.120
192.168.2.121,Art-Net,Pixel,4,Stage
{192.168.2.121 Art-Net Pixel 4} {Stage}
No more messages.

@nuc-i5:/development$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)
```

**Comment by hippyau** [comment]
Thank you.  Indeed an observation, understood that it's AS-IS.   It will be simple to eventually make my own UI to share, thanks to your hard work! 

I can see in Wireshark the requests go out to broadcast, and answers come back, but they never make it into the UI for some reason.    I just tried jdk 1.8.0_212 as well.    

If I get any further with this I'll report back.

**Comment by vanvught** [comment]
> Thank you. Indeed an observation, understood that it's AS-IS. It will be simple to eventually make my own UI to share, thanks to your hard work!

Thanks! It would be great to see an improved UI. Thanks.

> I can see in Wireshark the requests go out to broadcast, and answers come back, but they never make it into the UI for some reason. I just tried jdk 1.8.0_212 as well.

Maybe a time-out issue? Somehow odd that the response is not consumed.

> If I get any further with this I'll report back.

Please do. Although the Java UI is AS-IS, I am eager to know what is happening here.

**Comment by vanvught** [comment]
Hi @hippyau , do you still having the issue? Please will you check the latest .jar file? Thanks, Arjan

**Comment by hippyau** [comment]
Hi Arjan,
   I pulled about a week ago and noticed it is working now.  Thanks!
Cheers,
  Hippy
