### ISSUE TITLE
uImage.gz

### ISSUE THREAD

**Issue by drummerclint** [vanvught/h3dmx512-zip#5]
Thanks for all the great work Arjan!  I was gonna try the new LTC release but I can't unzip the orangepi_zero.uImage.gz file once it's out of the .zip.  I tried it in both 7zip in windows and gunzip in unix.  Tried redownloading the file as well to see if it would help.  Not sure what I'm missing.  Looking forward to trying out the new features you've added with James.

Thanks,
Clint

**Comment by vanvught** [comment]
Hi Clint,

Thanks for the compliments. Much appreciated. 

When you are working with the SDCard, then copy file `orangepi_zero.uImage.gz` to the SDCard as `uImage`.

When you have already a running firmware, then use the `./do-tftp.sh` script with parameter of the target IP-address. 
For example:
` ./do-tftp.sh 192.168.2.252`

Alternatively, the sample Java UI can be used for upgrading the firmware.

- Action -> TFTP On
- Run -> TFTP client -> Select uImage -> TFTP Put
- Action -> TFTP Off {at this point, the newly uploaded firmware is written to SPI flash}
- Action -> Reboot

In https://github.com/vanvught/rpidmx512/issues/89 I have already support for pitch control with UDP messages. The source code is available in the staging branch.

-Arjan

**Comment by drummerclint** [comment]
Thanks Arjan, renaming it did the trick!

-Clint
