### ISSUE TITLE
How to LTC In ?

### ISSUE THREAD

**Issue by lyon470** [vanvught/h3dmx512-zip#7]
Hello
Very nice work !
I using the LTC SMPTE Firmware and sending LTC very nice.
But now i try to read LTC an wondering how to get the Audio in ?
For Output of the LTC i use a Orange Pi Zero an the Zero Interface Board.
Can i also receive LTC with this board ?

Thanks a lot

**Comment by vanvught** [comment]
Hi @lyon470 

> But now i try to read LTC an wondering how to get the Audio in ?

I have simple unbalanced example here -> http://www.orangepi-dmx.org/orange-pi-smpte-timecode-ltc-reader-converter/hardware

I am working on a proper balanced input (and output). Please keep an eye on my website for that publication.

Thanks, Arjan

**Comment by lyon470** [comment]
Thanks for your fast reply.
I looked at your schematic and i‘m not sure i got it right.


![image](https://user-images.githubusercontent.com/40247428/77153990-24e9d200-6a9b-11ea-994f-43c990d92de8.jpg)

Is this right how i draw it?
Thanks a lot for your Service

**Comment by vanvught** [comment]
> Thanks for your fast reply.

You're welcome!

> Is this right how i draw it?

Yes. Note that the VDD for the OPAMP is 3V3. And basically any rail-to-rail OPAMP can be used.
Background information: [https://www.analogictips.com/amplifiers-rail-to-rail-single-supply-mean/](https://www.analogictips.com/amplifiers-rail-to-rail-single-supply-mean/)

**Comment by vanvught** [comment]
Hi @lyon470, is it working for you? Thanks, Arjan

**Comment by vanvught** [comment]
Please re-open when further assistance is needed. Thanks, Arjan
