### ISSUE TITLE
help configuring orange pi zero

### ISSUE THREAD

**Issue by chillywillywonka** [vanvught/h3dmx512-zip#9]
Hi!

Thanks for all the work you've put into this. It's great!

I've ordered a usb dmx board for a Pi initially, but then got a orange pi zero, because you mentioned it's better supported. 

I'm happy to say it's working! I've installed the artnet image. And I can send artnet and control a dmx lamp via the dmx output. 
The only thing, which is maybe because of my noobness, is that I can't seem to configure the orange pi zero. 

The remoteConfigUI is seeing the DMX node. But when I change something in the txt files and right click to save nothing is changed. The reboot command is working though. 

I've also tried via the terminal to send txt files or requests but nothing happens. I do put the the ipaddress in which is shown in the remoteConfigUi. 
Tried it with java -jar remoteConfigui.jar. Then I see it's sending a doSave command with the changes I've made. But it just doesn't stick on reboot. I reboot without the card in btw. 

It seems to me the SPI Flash isn't reachable or something? (noobness alert)

My goal is to change the Ip into a static Ip. 

The screenshot is what I see in the remoteConfigUi. 

![Screenshot 2020-10-02 at 10 47 39](https://user-images.githubusercontent.com/19151054/94905188-bdc2c680-049c-11eb-991c-98640e3b525a.png)

Thanks,

Wilco

**Comment by vanvught** [comment]
Hi Wilco,

Thanks for compliments. Much appreciated. 

When using the Remote Configuration Framework (the sample Java application), the .txt files on the SDCard takes precedence so any changes you make with this Framework will get overwritten by the .txt files on the SDCard if it exists. You only need the SDCard for the initial setup.

Greets, Arjan

**Comment by chillywillywonka** [comment]
Hi Arjan,

Thanks for your swift reply. 

That's what I'm doing actually. I only use the SDCard for the initial setup. 

Is it so that when during the initial setup the network.txt is changed, that change is uploaded to the SPI Flash? 
Because that didn't work for me either. It just shows network.txt with DHCP=1 and the rest with zeros. 

So to be clear. I'm trying to update the network.txt through the remoteConfigUi.jar without a card inserted. And it isn't uploaded to the orange pi zero. 
Is there a check I can do to make sure everything is working?

Thanks (bedankt ;)

Wilco

**Comment by vanvught** [comment]
Hoi Wilco,

As you can boot without the SDCard (which I misread;) , then the SPI flash is fine.
Have you removed the "#" for the new network.txt settings?

When you have saved the new settings, then do a View->Refresh , then the new settings should be visible. And applied after a reboot.

Groet, Arjan

**Comment by chillywillywonka** [comment]
Yes! 
Embarrassed to say, I indeed forgot to take out the '#'. 
It works. 
Great, thanks for your help!

Groet, 

Wilco
